# Generated by Django 3.2.11 on 2022-02-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_has_beta_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
