# Generated by Django 3.2.12 on 2022-03-09 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_q", "0014_schedule_cluster"),
        ("users", "0003_customuser_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="next_notification",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_q.schedule",
            ),
        ),
    ]
