# Generated by Django 3.2.12 on 2022-03-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_next_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="locale",
            field=models.CharField(
                choices=[("de", "Deutsch"), ("en", "Englisch")], max_length=2, null=True
            ),
        ),
    ]
