default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier