version: "3"

services:
  db:
    container_name: postgres
    image: postgres:12.8
    env_file:
      - .env.compose
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  app:
    container_name: spritstat
    image: ghcr.io/tgamauf/spritstat:latest
    env_file:
      - .env.compose
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - staticfiles:/home/app/web/staticfiles
  nginx:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - staticfiles:/home/app/web/staticfiles/
      - ./nginx/vhost.d/:/etc/nginx/vhost.d/
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - app

volumes:
  postgres:
  staticfiles:
