# Generated by Django 4.1.5 on 2023-01-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_statistics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyactiveusers",
            name="date",
            field=models.DateField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="monthlyactiveusers",
            name="date",
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
