# Generated by Django 3.2.6 on 2022-01-03 14:00

from django.conf import settings
from django.contrib.sites.models import Site
from django.db import migrations, models
import django.db.models.deletion


def set_site(apps, schema_editor):
    # Update the site from the DOMAIN value of our environment
    domain = settings.DOMAIN

    Site.objects.create(id=settings.SITE_ID, domain=domain, name=domain)


class Migration(migrations.Migration):
    replaces = [
        ("spritstat", "0001_initial"),
        ("spritstat", "0002_initial"),
        ("spritstat", "0003_auto_20211202_1655"),
        ("spritstat", "0004_alter_station_id"),
        ("spritstat", "0005_auto_20211221_1957"),
        ("spritstat", "0006_remove_price_user"),
        ("spritstat", "0007_fix_configured_site_name"),
        ("spritstat", "0008_fix_configured_site_name_again"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_q", "0014_schedule_cluster"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=80)),
                ("postal_code", models.CharField(max_length=4)),
                ("city", models.CharField(max_length=30)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "Coordinates"), (1, "Address"), (2, "Region")]
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=9, null=True
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=80)),
                ("postal_code", models.CharField(blank=True, max_length=4)),
                ("city", models.CharField(blank=True, max_length=30)),
                ("region_code", models.IntegerField(blank=True, null=True)),
                (
                    "region_type",
                    models.CharField(
                        blank=True,
                        choices=[("BL", "Bundesland"), ("PB", "Bezirk")],
                        max_length=2,
                    ),
                ),
                ("region_name", models.CharField(blank=True, max_length=50)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[("DIE", "Diesel"), ("SUP", "Super"), ("GAS", "Gas")],
                        max_length=10,
                    ),
                ),
                (
                    "schedule",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_q.schedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                ("min_amount", models.FloatField()),
                ("max_amount", models.FloatField()),
                ("average_amount", models.FloatField()),
                ("median_amount", models.FloatField()),
                (
                    "cheapest_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spritstat.station",
                    ),
                ),
                (
                    "user_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="spritstat.userlocation",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="userlocation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("address__exact", ""),
                        ("city__exact", ""),
                        ("latitude__isnull", False),
                        ("longitude__isnull", False),
                        ("postal_code__exact", ""),
                        ("region_code__isnull", True),
                        ("region_name__exact", ""),
                        ("region_type__exact", ""),
                        ("type", 0),
                    ),
                    models.Q(
                        ("address__length__gt", 0),
                        ("city__length__gt", 0),
                        ("latitude__isnull", False),
                        ("longitude__isnull", False),
                        ("postal_code__length__gt", 0),
                        ("region_code__isnull", True),
                        ("region_name__exact", ""),
                        ("region_type__exact", ""),
                        ("type", 1),
                    ),
                    models.Q(
                        ("address__exact", ""),
                        ("city__exact", ""),
                        ("latitude__isnull", True),
                        ("longitude__isnull", True),
                        ("postal_code__exact", ""),
                        ("region_code__isnull", False),
                        ("region_name__length__gt", 0),
                        ("region_type__length__gt", 0),
                        ("type", 2),
                    ),
                    _connector="OR",
                ),
                name="spritstat_userlocation_value_matches_type",
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.customuser",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_site),
    ]
