# Generated by Django 3.2.10 on 2022-01-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spritstat", "0001_squashed_0008_fix_configured_site_name_again"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="cheapest_station",
        ),
        migrations.AddField(
            model_name="price",
            name="stations",
            field=models.ManyToManyField(related_name="prices", to="spritstat.Station"),
        ),
    ]
