# Generated by Django 3.2.10 on 2022-01-08 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_q", "0014_schedule_cluster"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("spritstat", "0002_auto_20220107"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserLocation",
            new_name="Location",
        ),
        migrations.RemoveConstraint(
            model_name="location",
            name="spritstat_userlocation_value_matches_type",
        ),
        migrations.RenameField(
            model_name="price",
            old_name="user_location",
            new_name="location",
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("address__exact", ""),
                        ("city__exact", ""),
                        ("latitude__isnull", False),
                        ("longitude__isnull", False),
                        ("postal_code__exact", ""),
                        ("region_code__isnull", True),
                        ("region_name__exact", ""),
                        ("region_type__exact", ""),
                        ("type", 0),
                    ),
                    models.Q(
                        ("address__length__gt", 0),
                        ("city__length__gt", 0),
                        ("latitude__isnull", False),
                        ("longitude__isnull", False),
                        ("postal_code__length__gt", 0),
                        ("region_code__isnull", True),
                        ("region_name__exact", ""),
                        ("region_type__exact", ""),
                        ("type", 1),
                    ),
                    models.Q(
                        ("address__exact", ""),
                        ("city__exact", ""),
                        ("latitude__isnull", True),
                        ("longitude__isnull", True),
                        ("postal_code__exact", ""),
                        ("region_code__isnull", False),
                        ("region_name__length__gt", 0),
                        ("region_type__length__gt", 0),
                        ("type", 2),
                    ),
                    _connector="OR",
                ),
                name="spritstat_location_value_matches_type",
            ),
        ),
    ]
