# Generated by Django 3.2.10 on 2022-01-08 12:11

from django.db import migrations


def replace_schedule_function(apps, schema_editor):
    Schedule = apps.get_model("django_q", "Schedule")
    for schedule in Schedule.objects.all():
        schedule.func = "spritstat.services.request_location_prices"
        schedule.save()


class Migration(migrations.Migration):
    dependencies = [
        ("spritstat", "0003_auto_20220108_1200"),
    ]

    operations = [migrations.RunPython(replace_schedule_function)]
