# Generated by Django 3.2.10 on 2022-01-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spritstat", "0004_auto_20220108_1211"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
