# Generated by Django 3.2.10 on 2022-01-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spritstat", "0005_alter_price_datetime"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="location",
            name="spritstat_location_value_matches_type",
        ),
        migrations.AlterField(
            model_name="location",
            name="type",
            field=models.IntegerField(choices=[(1, "Address"), (2, "Region")]),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("address__length__gt", 0),
                        ("city__length__gt", 0),
                        ("latitude__isnull", False),
                        ("longitude__isnull", False),
                        ("postal_code__length__gt", 0),
                        ("region_code__isnull", True),
                        ("region_name__exact", ""),
                        ("region_type__exact", ""),
                        ("type", 1),
                    ),
                    models.Q(
                        ("address__exact", ""),
                        ("city__exact", ""),
                        ("latitude__isnull", True),
                        ("longitude__isnull", True),
                        ("postal_code__exact", ""),
                        ("region_code__isnull", False),
                        ("region_name__length__gt", 0),
                        ("region_type__length__gt", 0),
                        ("type", 2),
                    ),
                    _connector="OR",
                ),
                name="spritstat_location_value_matches_type",
            ),
        ),
    ]
