# Generated by Django 3.2.11 on 2022-01-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spritstat", "0008_auto_20220127_1243"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
