# Generated by Django 3.2.11 on 2022-02-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spritstat", "0008_auto_20220127_1243"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="address",
        ),
        migrations.RemoveField(
            model_name="location",
            name="city",
        ),
        migrations.RemoveField(
            model_name="location",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="location",
            name="region_name",
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
