# Generated by Django 3.2.11 on 2022-02-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spritstat", "0009_auto_20220201_1729"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.CharField(max_length=80),
        ),
    ]
