# Generated by Django 3.2.11 on 2022-02-03 15:09

from django.db import migrations
from django_q.tasks import schedule, Schedule


def add_clear_session_task(apps, schema_editor):
    schedule(
        "spritstat.services.clear_expired_sessions",
        schedule_type=Schedule.DAILY,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("spritstat", "0010_alter_station_name"),
    ]

    operations = [migrations.RunPython(add_clear_session_task)]
