# Generated by Django 3.2.11 on 2022-02-10 20:40

from django.conf import settings
from django.db import migrations, models


def assing_stations_to_users(apps, schema_editor):
    CustomUser = apps.get_model("users", "CustomUser")
    for user in CustomUser.objects.all():
        stations = set()
        for location in user.locations.all():
            for price in location.prices.all():
                stations.update(price.stations.all())

        user.stations.add(*stations)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("spritstat", "0012_auto_20220210_2059"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="users",
            field=models.ManyToManyField(
                related_name="stations", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(assing_stations_to_users),
    ]
