# Generated by Django 3.2.12 on 2022-03-09 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("spritstat", "0017_introsettings_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="notifications_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
