# Generated by Django 3.2.12 on 2022-03-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spritstat", "0020_alter_location_schedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="intro",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spritstat.introsettings",
            ),
        ),
    ]
