name: Deploy

#on:
#  workflow_run: TODO
#    workflows: [Test]
#    types: [completed]
#    branches: [main]
on: push
env:
  IMAGE_NAME: "ghcr.io/tgamauf/spritstat"
  DEPLOYMENT_REPO: "tgamauf/spritstat-deployment"
  DEPLOYMENT_FILE_PATH: "k8s/spritstat/deployment.yaml"

jobs:
  docker:
    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }} TODO
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=sha
#          flavor: latest=true TODO
      - name: Login to Github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    outputs:
      image_version: ${{ steps.meta.outputs.version }}
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout spritstat-deployment
        uses: actions/checkout@v3
        with:
          repository: ${{ env.DEPLOYMENT_REPO }}
          ref: ${{ github.ref_name }}
          token: ${{ secrets.SPRITSTAT_DEPLOYMENT_TOKEN }}
      - name: Install Python dependencies
        run: pip install PyYAML
      - name: Update deployed version
        shell: python
        run: |
          from os import environ
          import yaml
          
          print(environ)
          
          deployment_path = environ["DEPLOYMENT_FILE_PATH"]
          image = environ["IMAGE"]
          with open(deployment_path) as f:
              data = yaml.safe_load(f)
          data["spec"]["template"]["spec"]["containers"][0]["image"] = image
          with open(deployment_path, "w") as f:
              data = yaml.safe_dump(data, f)
        env:
          IMAGE: "${{ env.IMAGE_NAME }}:${{ needs.docker.outputs.image_version }}"
      - name: Commit and push changes
        run: |
          git config user.name "SPRITSTAT Github Action"
          git config user.email "robot@farside.ai"
          git add ${DEPLOYMENT_FILE_PATH}
          git commit -m "Update SPRITSTAT image version to ${IMAGE_VERSION}"
          git push
        env:
          IMAGE_VERSION: "${{ needs.docker.outputs.image_version }}"
