name: Deploy

#on:
#  workflow_run: TODO
#    workflows: [Test]
#    types: [completed]
#    branches: [main]
on: push
env:
  image_name: "ghcr.io/tgamauf/spritstat"
  deployment_repo: "tgamauf/spritstat-deployment"
  deployment_path: "k8s/spritstat/deployment.yaml"

jobs:
  docker:
    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }} TODO
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.image_name }}
          tags: type=sha
#          flavor: latest=true TODO
      - name: Login to Github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Checkout spritstat-deployment
        uses: actions/checkout@v3
        with:
          repository:
          ref: ${{ github.ref_name }}
          token:
      - name: Install Python dependencies
        run: pip install PyYAML
      - name: Update deployed version
        shell: python
        run: |
          from os import environ
          import yaml
          
          print(environ)
          
          deployment_path = environ["INPUTS_DEPLOYMENT_PATH"]
          image = environ["INPUTS_IMAGE"]
          with open(deployment_path) as f:
              data = yaml.safe_load(f)
          data["spec"]["template"]["spec"]["containers"][0]["image"] = image
          with open(deployment_path, "w") as f:
              data = yaml.safe_dump(data, f)
        env:
          image: "${{ env.image }}:${{ steps.meta.outputs.version }}"
